---
- hosts: localhost
  gather_facts: no

  tasks:
  
  - name: Power On virtual machine on Azure
    azure_rm_virtualmachine:
      resource_group: "openenv-67smw-2"
      name: "SRVDEMO0001-AZURE"

