---
- name: Tasks
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  
  - name: Power On
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: openenv-v98rk-2
      name: SRVDEMO0001-AZURE
      started: true
