---
- name: Tasks 
  hosts: localhost
  gather_facts: no
  vars:
    instance_ids: undef

  tasks:
  
  - name: Iniciando uma instancia especifica pelo ID
    amazon.aws.ec2_instance:
      region: us-east-2
      state: "stopped"
      instance_ids:
        - "{{ instance_ids }}"
