---
- name: Check web app for Normal State
  uri:
    url: "http://3.129.238.169"
    return_content: yes
  register: webpage

- name: Falha se o status não esta normal
  fail:
  when: "'normal' not in webpage.content"
