---
- name: Check web app for Normal State
  uri:
    url: "http://bastion.67smw.sandbox2961.opentlc.com:8080"
    return_content: yes
  register: webpage

- name: Falha se o status não esta normal
  fail:
  when: "'Normal' not in webpage.content"
