---
- name: Check web app for DR State
  uri:
    url: "http://bastion.67smw.sandbox2961.opentlc.com:8080"
    return_content: yes
  register: webpage

- name: Falaha se o status DR nao esta em uso
  fail:
  when: "'DR' not in webpage.content"
