---
- name: Check web app for DR State
  uri:
    url: "http://20.228.154.228"
    return_content: yes
  register: webpage

- name: Falha se o status DR nao esta em uso
  fail:
  when: "'DR' not in webpage.content"
