---
- name: Check web app for DR State
  uri:
    url: "http://20.172.188.114"
    return_content: yes
  register: webpage

- name: Falha se o status DR nao esta em uso
  fail:
  when: "'DR' not in webpage.content"
