---
- hosts: localhost
  vars:
    status: undef
  tasks:
    - name: Checagem de status atual do Datacenter
      debug:
        msg: 'Status: "{{ status }}"' 
 
    - name: Falha se o status Datacenter nao esta OK
      fail:
      when: "'OK' not in status.content"
