---
- hosts: localhost
  vars:
    dc_status: undef
  tasks:
    - name: Checagem de status atual do Datacenter
      debug:
        msg: 'Status: "{{ status }}"' 
 
    - name: Falha se o status Datacenter nao esta OK
      ansible.builtin.fail:
        msg: O Datacenter primário está com status de falha.
      when: dc_status != "OK"

